# Generated by Django 3.2.13 on 2022-11-28 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221120_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9._]{3,}$', 'Username is invalid. Only lowercase English letters, period and underscore characters are allowed. Minimum length is three characters.')], verbose_name='Username'),
        ),
    ]
