# Generated by Django 3.1.7 on 2022-04-17 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="rating",
            field=models.ManyToManyField(
                related_name="post_rating",
                through="posts.Rate",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
