# Generated by Django 3.1.7 on 2022-04-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_auto_20220427_1653"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1
            ),
        ),
    ]
