version: "3.4"
services:
  sole_app:
    build: .
    image: sole_app
    container_name: sole_app
    volumes:
      - ".:/sole"
      - ".data/root:/root"
    depends_on:
      - sole_db
    ports:
      - "80:8000"

  sole_db:
    image: postgres:13.6
    environment:
      - POSTGRES_DB=sole_db
      - POSTGRES_USER=jay
      - POSTGRES_PASSWORD=test
    container_name: sole_postgres
    volumes:
      - ".data/db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
