# Generated by Django 3.2.13 on 2022-11-20 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glimpses', '0003_auto_20221120_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glimpse',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='glimpse',
            name='rating',
        ),
        migrations.AddField(
            model_name='glimpse',
            name='ratings',
            field=models.ManyToManyField(related_name='rated_glimpses', through='glimpses.Rating', to=settings.AUTH_USER_MODEL, verbose_name='Ratings'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='glimpse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glimpses.glimpse'),
        ),
        migrations.AlterField(
            model_name='like',
            name='glimpse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glimpses.glimpse'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='glimpse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glimpses.glimpse'),
        ),
    ]
