# Generated by Django 3.2.13 on 2022-11-29 16:41

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glimpses', '0004_auto_20221120_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, max_length=255, populate_from='name', verbose_name='Slug')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RenameField(
            model_name='glimpse',
            old_name='created_by',
            new_name='author',
        ),
        migrations.AddField(
            model_name='glimpse',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated on'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, default='', editable=False, max_length=255, populate_from='name', verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
