# Generated by Django 3.2.13 on 2022-11-28 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('glimpses', '0004_auto_20221120_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='tag',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=255, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
