# Generated by Django 3.2.13 on 2022-11-29 18:48

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glimpses', '0005_auto_20221128_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, max_length=255, populate_from='name', verbose_name='Slug')),
            ],
        ),
        migrations.RenameField(
            model_name='glimpse',
            old_name='created_by',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='creation_datetime',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='update_datetime',
        ),
        migrations.AddField(
            model_name='glimpse',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated on'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(allow_unicode=True, editable=False, max_length=255, populate_from='name', verbose_name='Slug'),
        ),
    ]
