# Generated by Django 3.2.13 on 2022-11-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glimpses', '0006_auto_20221129_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glimpse',
            name='text',
            field=models.TextField(blank=True, max_length=255, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='glimpse',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
