# Generated by Django 3.2.13 on 2022-12-19 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('glimpses', '0011_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='glimpse',
            name='category',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('reading', 'Reading'), ('event', 'Event'), ('place', 'Place'), ('app', 'Application'), ('other', 'Other')], max_length=255, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='glimpse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='space',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
