version: "3.4"
services:
  sole_app:
    build: .
    image: sole_app
    container_name: sole_app
    volumes:
      - ".:/sole"
      - ".data/root:/root"
    depends_on:
      - postgres
    ports:
      - "3500:3500"
    tty: true

  postgres:
    image: postgres:13.6
    environment:
      - POSTGRES_DB=sole
      - POSTGRES_USER=sole_dbu
      - POSTGRES_PASSWORD=test
    container_name: sole_postgres
    volumes:
      - ".data/db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --quiet || exit 1"]
      interval: 1m
      timeout: 30s
      retries: 10
      start_period: 40s
    restart: on-failure