name: Linters

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install flake8
      - name: flake8
        # Pinned to v1.0.2.
        uses: liskin/gh-problem-matcher-wrap@e7d110d699a16b3dead9ef8b1f9470f93765ae95
        with:
          linters: flake8
          run: flake8

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python -m pip install isort
      - name: isort
        # Pinned to v1.0.2.
        uses: liskin/gh-problem-matcher-wrap@e7d110d699a16b3dead9ef8b1f9470f93765ae95
        with:
          linters: isort
          run: isort --check --diff django tests scripts

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: black
        uses: psf/black@stable