name: Tester CI

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - "3.11"

    services:
      postgres:
        image: postgres:13.6
        env:
          POSTGRES_USER: sole_dbu
          POSTGRES_PASSWORD: test
          POSTGRES_DB: sole
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        DEBUG: false
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        file_name: .env

      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r sole_project/requirements.txt
      - name: Run Tests
        run: |
          python sole_project/manage.py test
